on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup
        uses: pnpm/action-setup@v4
      - name: Install
        run: pnpm i
      - name: Test (Linux)
        run: xvfb-run -a pnpm t
        if: runner.os == 'Linux'
      - name: Test (non-Linux)
        run: pnpm t
        if: runner.os != 'Linux'
